---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: default
spec:
  encryptedData:
    PASSWORD: AgCWTT5H7m42fUVYRwVN0y7NJBrCYdyGlpluT6d+RJ+KGfekAgNkoR0asYJL9shvK0U+dM85ckDQgfbJ04ZzPWP74+tPkrGLNHeSHIWWSGmHWQyE1GthE4AB4meTLYv+6wiN6FFyA2OllVEnlrsgU/PefTtpsaOz0cwq4UIGNbEfs8zsRwHu8j9bhAvCfebfMYwuF+ezGUlUNx0cGRj7HepntD1tWfwPkUkAsrBl6f5Een5yIpzWYHvcnTEQD0eOIU+hOmVBnKe/7sFXsPMeI7jtbNhfS+qOxPHljJUIHk3S8B28JfP2Hvh9S9EWYQuDlO6Vnb4rL5WkZirKKEPt1iDGn5RR5GkBvlC2Fx7wp4AU/T+9iwHxcwukSMk6nSvb+JnBHjzJWAbv1L/NIPWDjvQ5sCc8zLb2DKOszMbMRigx2rozLx0/U7OYs49bxWD9GIPqVVQL+hOCxg3MOaBoJSkBMv3mCIyRKmXXtxh2oZhaFzsjEM9+xhBs1MQnhbU0fZmNVzv95nUdQfjbbLTZCXwfpcE3gwpuI1mGiWgE0qrL8LZhtq1x4dQ3KT58w5vii835e0ZX5YiP5Xa/fYDsAG2THFMHGHMqrBniIdL3yqNH/2M+x0bwAyJhvbx24RafnfEnxGWd/OkSC/6gD0Esh694N+zpJmt/uOmtuxQ1Yo7yEgfLV8Unag4y2/YRTIjfqZoNuzUFWwsCAhA+
  template:
    metadata:
      name: my-secret
      namespace: default
