---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: default
spec:
  encryptedData:
    PASSWORD: AgAfC8eN78L7tpoJAVPEfYk0DRZ9UDdInL6rtsz7Jm0l9keqtQZVDbmp+63g0vr81PJDJOzfZfE9CZJ1ez7Gp2gGNKvP6V/nbZ/LtHna2S6PmP4gyyssk9SKRejJMuqhtsg7cxhH07hpxaPCb1+/rfJ5KEEINdqwIDb4pX+yOYyv0LC1S8kG0oiDbE/k4Ia12A+L7HlC5neeEGAFz6gxwZRSW7lyCX6iYhaBikZ4LqNJZyoC2jUktxf+LCcMxwpNRyuqH5Byq3vKBq3iRlKeNPs0PS/V5lcjehJa7NmWOytDL01/AKy6xzQguwPMVduXxkxkZ15cioS69FA4X1RjqAfHbHHZOok+fNhUQRa0O3DtSZzgQk9sKMXys3vBhnuQ+9ZOuSJKd0OeWE4LlmtjFf5TnO+iQxKcOGTiPrE9Tgzohij2w4cfvDBYx9zFxJaUgPFRGpqbpwNmq1/ywDkgvRFoVZBuByBwdrGT9q2vbxblQWTgrgX32gvLJaNXDkvyOuS6Ia3USNEIALi85egaEkgCTS/S/ZE2P58Tiea5SNlGYNOkivJ9IxUyWBMYFqGe3JbTVejRBcfVGrTAlFrD2O4FH0jhKwrC/HW+E6JbFUz2watvQbBDMuQTUPv3W5mm6WRXKO3b54QkngpXmyOIEdroEyYHnbdmRhlBRkeSTPxR5qhSQ7zR8nhFp0phaHN1Lpd1wXmXxigWLzKt
  template:
    metadata:
      name: my-secret
      namespace: default
